### ISSUE TITLE
Question how to use

### ISSUE THREAD

**Issue by beegee-tokyo** [lbernstone/arduino-esp32-solo#1]
Great work! Love it. Have one SOLO that I got accidentally.

Is there any way to have both the "normal" Arduino-ESP32 and a "SOLO" Arduino-ESP32 installed parallel?

**Comment by lbernstone** [comment]
Not without some significant work both in IDF and arduino.  It is pretty deeply embedded in a number of the system files.

**Comment by beegee-tokyo** [comment]
Understand.
Anyway, the Solo seems to be rarely used. 
I got mine as a wrong delivery.
