### ISSUE TITLE
Arduino core for the ESP32 - 2.0.x

### ISSUE THREAD

**Issue by bfaliszek** [lbernstone/arduino-esp32-solo#10]
new version of Arduino core for the ESP32 has been released - 2.0.0 - https://github.com/espressif/arduino-esp32/releases/tag/2.0.0

**Comment by bfaliszek** [comment]
And 2.0.1 RC1

**Comment by bfaliszek** [comment]
it would be more convenient to create a tutorial on how to generate the necessary files by yourself

**Comment by JoJ123** [comment]
@bfaliszek Did you found already a solution?

**Comment by bfaliszek** [comment]
not yet. For now, I'm back to Arduino core 1.0.6

**Comment by bfaliszek** [comment]
2.0.1 - Arduino core for the ESP32 https://github.com/espressif/arduino-esp32/releases/tag/2.0.1

**Comment by sixtyfive** [comment]
Perhaps even more convenient would be to get support for the single-core chips into the core :-)

**Comment by bfaliszek** [comment]
Officially, support for ESP32-SOLO-1 has been added to the roadmap for version 2.2.0 - https://github.com/espressif/arduino-esp32/milestone/4

**Comment by ChuckMash** [comment]
Anyone have a workaround yet?

**Comment by lbernstone** [comment]
I have posted libraries for 2.0.2, but don't have a solo around to test it on.  If I get confirmation that the examples all build (especially bluetoothserial), then I'll make a release.
You can build the libraries for yourself using [lib-builder](https://docs.espressif.com/projects/arduino-esp32/en/latest/lib_builder.html).  The only thing that needs to be changed in sdkconfig is CONFIG_FREERTOS_UNICORE=y

**Comment by lbernstone** [comment]
Pretty sure this is working now, so I will close the issue.
