### ISSUE TITLE
the project stopped compiling :((

### ISSUE THREAD

**Issue by yuriy23** [lbernstone/arduino-esp32-solo#12]
c:/users/yuriy/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Yuriy\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4/tools/sdk/esp32/lib\libcxx.a(cxx_guards.cpp.obj):(.literal.__cxa_guard_acquire+0x1c): undefined reference to `xPortEnterCriticalTimeout'
c:/users/yuriy/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2-patch3/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Yuriy\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.4/tools/sdk/esp32/lib\libcxx.a(cxx_guards.cpp.obj): in function `__cxa_guard_acquire':
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port/xtensa/include/freertos/portmacro.h:578: undefined reference to `xPortEnterCriticalTimeout'
collect2.exe: error: ld returned 1 exit status

**Comment by lbernstone** [comment]
This project is no longer supported.  Please see https://github.com/lbernstone/arduino-esp32-solo/issues/11
