### ISSUE TITLE
Arduino IDE compile the code but upload not working

### ISSUE THREAD

**Issue by Razzorback225** [lbernstone/arduino-esp32-solo#6]
Hi, 

I recently made a flasher board for my esp32 solo 1 chips. I actually (and it took me some time to understand how to do that) can upload code with esp-idf.

But when I want to upload the code with the arduino IDE on the board, it doesn't seem to detect my board.

I replaced the required file in the Arduino15 directory with the ones provided in this repo and it is compiling well on arduino IDE but that's all.
![Capture d’écran (5)](https://user-images.githubusercontent.com/47690391/90739998-195f3900-e2cf-11ea-8e2d-d132737b3ed8.png)

I attached a screenshot of my actual configuration for the board in arduino IDE.

Thanks for any help provided

**Comment by lbernstone** [comment]
These errors have nothing to do with this library.  Search for solutions in the arduino-esp32 issues.
