### ISSUE TITLE
is 240 mhz config correct?

### ISSUE THREAD

**Issue by maa1370** [lbernstone/arduino-esp32-solo#9]
Hi
in sdkconfig.h, i see:
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ 240
and
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_240 1

as ESP32-SOLO-1 is using ESP32-S0WD (https://www.espressif.com/sites/default/files/documentation/esp32-solo-1_datasheet_en.pdf) which supports 160 mhz maximum regarding to the datasheet (https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf), shouldn't these values be changed?

note: i'm not using esp32 with arduino and i can't test anything, i just looked at your repo for checking configs for another project.

**Comment by lbernstone** [comment]
arduino-esp32 overrides the CONFIG_ value, so you can easily set it lower than 240 if you like.  I can assure you that it works, as I have run the generated firmware on a physical device.
